name: Generate Javadoc
on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch: {}
jobs:
    deploy-pages:
        name: Generate Javadoc
        runs-on: ubuntu-latest
        steps:
          - name: Set up JDK 11
            uses: actions/setup-java@v2
            with:
              java-version: '11.0.11'
              distribution: 'adopt'
          - uses: avinal/github-pages-deploy-action@v0.9
            with:  
              GITHUB_TOKEN: ${{ github.token }}
              LANGUAGE: "java11"
              MAKE_COMMAND: "./gradlew javadoc"
              PAGES_BRANCH: "gh-pages"
              BUILD_FROM: "master"
              DOCS_FOLDER: "build/docs/javadoc"
